services:
  pb:
    image: ghcr.io/yk-lab/pocketbase:latest
    command: [ "serve", "--http", "0.0.0.0:8090" ]
    volumes:
      - pb_data:/pb_data
    ports:
      - "${PORT:-8090}:8090"

volumes:
  pb_data:
