services:
  pb:
    build:
      context: .
      args:
        - VERSION=0.2.7
        - PORT=${PORT:-8090}
    volumes:
      - pb_data:/pb_data
    ports:
      - "${PORT:-8090}:${PORT:-8090}"

volumes:
  pb_data:
